const RANDOM_THUMBNAILS_COUNT = 10;
const CHUNK_LOAD_COMMENTS = 5;
const MAX_LENGTH_COMMENT = 140;
const MAX_HASHTAGS = 5;
const SLIDER_INITIAL_MIN = 0;
const SLIDER_INITIAL_MAX = 100;
const SLIDER_INITIAL_STEP = 1;

export {
  RANDOM_THUMBNAILS_COUNT,
  CHUNK_LOAD_COMMENTS,
  MAX_LENGTH_COMMENT,
  MAX_HASHTAGS,
  SLIDER_INITIAL_MIN,
  SLIDER_INITIAL_MAX,
  SLIDER_INITIAL_STEP
};
